# Third-party imports
import readchar
from rich.console import Console
from rich.table import Table

# Create an instance of rich console to use it's custom methods
console: Console = Console()


def choose_commit(commits: list[str]) -> str:
    """
    Prompt the user to select a commit message from a list of suggestions.

    Args:
        commits (list[str]):
            A list of commit message suggestions generated by the AI.

    Returns:
        str:
            The commit message selected by the user.

    Raises:
        KeyboardInterrupt:
            If the user cancels the prompt (e.g. Ctrl+C).
    """

    index: int = 0

    while True:
        console.clear()

        table: Table = Table(show_header=False, box=None, pad_edge=False)

        for i, commit in enumerate(commits):
            if i == index:
                table.add_row(f"[green]> {commit}[/green]")
            else:
                table.add_row(f"  {commit}")

        console.print("\n[bold]Proposed commit messages[/bold]\n")
        console.print(table)
        console.print(
            "\n[dim]Use ↑ ↓ to move • Enter to select • Ctrl+C to cancel[/dim]"
        )

        key: str = readchar.readkey()

        if key == readchar.key.UP:
            index: int = (index - 1) % len(commits)

        elif key == readchar.key.DOWN:
            index: int = (index + 1) % len(commits)

        elif key == readchar.key.ENTER:
            return commits[index]

        elif key == readchar.key.CTRL_C:
            raise KeyboardInterrupt("Commit selection aborted by user.")
